/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application

    eclipse
    id("com.github.johnrengelman.shadow") version "5.2.0"
    id("de.gliderpilot.jnlp") version "1.2.6"
    id("edu.sc.seis.macAppBundle")version "2.3.0"

}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {

    // hibernate as a JPA implementation
    implementation("org.hibernate:hibernate-core:5.4.12.Final")
    implementation("org.hibernate:hibernate-tools:5.4.12.Final")
    implementation("org.hibernate:hibernate-entitymanager:5.4.12.Final")
    implementation("org.javassist:javassist:3.27.0-GA")


    implementation("javax.xml.bind:jaxb-api:2.3.0")
    implementation("javax.activation:activation:1.1.1")
    implementation("com.sun.xml.bind:jaxb-impl:2.3.0")
    implementation("com.sun.xml.bind:jaxb-core:2.3.0")

    implementation("com.h2database:h2:1.4.200")

    implementation("org.jgroups:jgroups:4.2.3.Final")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
}

tasks.jar {
    manifest {
        attributes("Main-Class: org.suivicovid.SuiviCovid")
    }
}

tasks.withType<JavaCompile> {
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"
}


macAppBundle {
    mainClassName = "org.suivicovid.SuiviCovid"
    bundleJRE = true
    javaProperties.put("apple.laf.useScreenMenuBar", "true")
}

application {
    mainClassName = "org.suivicovid.SuiviCovid"
}

val test by tasks.getting(Test::class) {
    useJUnitPlatform()
}
